export const nodes = [
  { id: "Estudante/Inquilino", group: "user", color: "blue" },
  { id: "Proprietário", group: "user", color: "green" },
  { id: "Tela Inicial", group: "system", color: "red" },
  { id: "Acomodação 1", group: "property", color: "orange" },
  { id: "Acomodação 2", group: "property", color: "orange" },
  { id: "Sistema de Avaliação", group: "system", color: "gray" },
  { id: "Sistema de Login", group: "system", color: "pink" },
  { id: "Sistema de Cadastro Proprietário", group: "system", color: "purple" },
  { id: "Sistema de Cadastro Estudante", group: "system", color: "purple" },
  { id: "Sistema de Chat", group: "system", color: "brown" },
  { id: "Sistema de Banco de Dados", group: "system", color: "yellow" },
  { id: "Sistema de Busca", group: "system", color: "cyan" },
  { id: "Contato", group: "system", color: "magenta" },
  { id: "Dúvida", group: "system", color: "lightgreen" },
  { id: "Tela Principal", group: "system", color: "lightblue" },
  { id: "Sistema Cadastro de locais", group: "system", color: "coral"},
  { id: "Sistema de Verificação de dados", group: "system", color: "beige"},
  { id: "Sistema de gerenciamento do perfil", group: "system", color: "teal"}
];

export const links = [
  { source: "Tela Inicial", target: "Estudante/Inquilino"},
  { source: "Tela Inicial", target: "Proprietário" },
  { source: "Tela Inicial", target: "Sistema de Login", type: "access" },
  { source: "Sistema de Login", target: "Sistema de Cadastro Estudante", type: "register" },
  { source: "Sistema de Login", target: "Sistema de Cadastro Proprietário", type: "register" },
  { source: "Sistema de Busca", target: "Acomodação 1", type: "search" },
  { source: "Sistema de Busca", target: "Acomodação 2", type: "search" },
  { source: "Sistema de Busca", target: "Tela Principal", type: "owns" },
  { source: "Sistema de Verificação de dados", target: "Acomodação 1", type: "review"},
  { source: "Sistema de Verificação de dados", target: "Acomodação 2", type: "review"},
  { source: "Sistema Cadastro de locais", target: "Sistema de gerenciamento do perfil", type: "owns"},
  { source: "Sistema Cadastro de locais", target: "Acomodação 1", type: "register"},
  { source: "Sistema Cadastro de locais", target: "Acomodação 2", type: "register"},
  { source: "Sistema de Cadastro Estudante", target: "Sistema de Banco de Dados", type: "owns" },
  { source: "Sistema de Cadastro Proprietário", target: "Sistema de Banco de Dados", type: "owns" },
  { source: "Sistema de Avaliação", target: "Sistema de Banco de Dados", type: "owns" },
  { source: "Sistema de Avaliação", target: "Acomodação 1", type: "rate" },
  { source: "Sistema de Avaliação", target: "Acomodação 2", type: "rate" },
  { source: "Tela Principal", target: "Sistema de Login", type: "access" },
  { source: "Sistema de Chat", target: "Acomodação 1", type: "message" },
  { source: "Sistema de Chat", target: "Acomodação 2", type: "message" },
  { source: "Sistema de gerenciamento do perfil", target: "Tela Principal", type: "owns"},
  { source: "Sistema de gerenciamento do perfil", target: "Contato", type: "register"},
  { source: "Dúvida", target: "Contato", type: "question"},
  { source: "Sistema de Banco de Dados", target: "Acomodação 1", type: "owns"},
  { source: "Sistema de Banco de Dados", target: "Acomodação 2", type: "owns"},
  { source: "Sistema de Banco de Dados", target: "Acomodação 1", type: "owns"},
  { source: "Sistema de Banco de Dados", target: "Sistema de Login", type: "owns"},
  { source: "Sistema de Banco de Dados", target: "Sistema de Chat", type: "owns"},
  { source: "Sistema de Banco de Dados", target: "Sistema de Busca", type: "owns"},
  { source: "Sistema de Banco de Dados", target: "Contato", type: "owns"},
  { source: "Sistema de Banco de Dados", target: "Dúvida", type: "owns"},
  { source: "Sistema de Banco de Dados", target: "Tela Principal", type: "owns"},
  { source: "Sistema de Banco de Dados", target: "Sistema Cadastro de locais", type: "owns"},
  { source: "Sistema de Banco de Dados", target: "Sistema de Verificação de dados", type: "owns"},
  { source: "Sistema de Banco de Dados", target: "Sistema de gerenciamento do perfil", type: "owns"},
  { source: "Sistema de Banco de Dados", target: "Tela Inicial", type: "owns"},
  { source: "Sistema de Banco de Dados", target: "Proprietário", type: "owns"},
  { source: "Sistema de Banco de Dados", target: "Estudante/Inquilino", type: "owns"},
];
